// Sample website projects data
export const websiteProjects = [
  {
    id: 1,
    title: "E-commerce Platform",
    description: "A modern e-commerce platform with integrated payment systems",
    src: "/images/portfolio/websites/ecommerce.jpg",
    alt: "E-commerce Website Screenshot",
    link: "/web-development",
  },
  {
    id: 2,
    title: "Corporate Website",
    description: "Professional website for a financial services company",
    src: "/images/portfolio/websites/corporate.jpg",
    alt: "Corporate Website Screenshot",
    link: "/web-development",
  },
  {
    id: 3,
    title: "Portfolio Site",
    description: "Creative portfolio for a photography studio",
    src: "/images/portfolio/websites/portfolio.jpg",
    alt: "Portfolio Website Screenshot",
    link: "/web-development",
  },
  {
    id: 4,
    title: "Restaurant Ordering",
    description: "Online ordering system for a local restaurant",
    src: "/images/portfolio/websites/restaurant.jpg",
    alt: "Restaurant Website Screenshot",
    link: "/web-development",
  },
  {
    id: 5,
    title: "Fitness Tracker",
    description: "Web application for tracking workouts and nutrition",
    src: "/images/portfolio/websites/fitness.jpg",
    alt: "Fitness App Screenshot",
    link: "/web-development",
  },
  {
    id: 6,
    title: "Event Booking",
    description: "Ticket booking platform for events and conferences",
    src: "/images/portfolio/websites/events.jpg",
    alt: "Event Booking Website Screenshot",
    link: "/web-development",
  },
]; 